server:
  port: 8082
    
# My SQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_02_2022_clientes?serverTimezone=GMT-6
    username: dbatsi
    password: tsystem
    driverClassName: com.mysql.cj.jdbc.Driver
  
# Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"